//
//  Zone_in-Swift.h
//  Zone'in
//
//  Created by Rean on 10/24/15.
//  Copyright © 2015 Rean. All rights reserved.
//
// Generated by Apple Swift version 2.1 (swiftlang-700.1.101.6 clang-700.1.76)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if defined(__has_include) && __has_include(<uchar.h>)
# include <uchar.h>
#elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
#endif

typedef struct _NSZone NSZone;

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
#endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
#if defined(__has_feature) && __has_feature(modules)
@import UIKit;
@import ObjectiveC;
@import CoreGraphics;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
@class UIWindow;
@class Singleton;
@class UIApplication;
@class NSObject;

SWIFT_CLASS("_TtC7Zone_in11AppDelegate")
@interface AppDelegate : UIResponder <UIApplicationDelegate>
@property (nonatomic, strong) UIWindow * __nullable window;
@property (nonatomic, readonly, strong) Singleton * __nonnull sharedData;
- (BOOL)application:(UIApplication * __nonnull)application didFinishLaunchingWithOptions:(NSDictionary * __nullable)launchOptions;
- (void)applicationWillResignActive:(UIApplication * __nonnull)application;
- (void)applicationDidEnterBackground:(UIApplication * __nonnull)application;
- (void)applicationWillEnterForeground:(UIApplication * __nonnull)application;
- (void)applicationDidBecomeActive:(UIApplication * __nonnull)application;
- (void)applicationWillTerminate:(UIApplication * __nonnull)application;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIStoryboardSegue;
@class UILabel;
@class NSBundle;
@class NSCoder;

SWIFT_CLASS("_TtC7Zone_in20BuyOneViewController")
@interface BuyOneViewController : UIViewController
@property (nonatomic) NSInteger money;
@property (nonatomic, weak) IBOutlet UILabel * __null_unspecified moneyLabel;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (IBAction)seaweedAct:(id __nonnull)sender;
- (IBAction)cleaningSetAct:(id __nonnull)sender;
- (IBAction)funnyCatAct:(id __nonnull)sender;
- (IBAction)pipeAct:(id __nonnull)sender;
- (IBAction)pillAct:(id __nonnull)sender;
- (void)prepareForSegue:(UIStoryboardSegue * __nonnull)segue sender:(id __nullable)sender;
- (IBAction)toBuyOneViewController:(UIStoryboardSegue * __nonnull)segue;
- (IBAction)close;
- (nonnull instancetype)initWithNibName:(NSString * __nullable)nibNameOrNil bundle:(NSBundle * __nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7Zone_in20BuyTwoViewController")
@interface BuyTwoViewController : UIViewController
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (nonnull instancetype)initWithNibName:(NSString * __nullable)nibNameOrNil bundle:(NSBundle * __nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UITextField;

SWIFT_CLASS("_TtC7Zone_in29CheckFirstLoginViewController")
@interface CheckFirstLoginViewController : UIViewController
@property (nonatomic, weak) IBOutlet UITextField * __null_unspecified nameLabel;
@property (nonatomic, weak) IBOutlet UILabel * __null_unspecified warningLabel;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (IBAction)takeTutorialAct:(id __nonnull)sender;
- (void)jumpToTimer;
- (nonnull instancetype)initWithNibName:(NSString * __nullable)nibNameOrNil bundle:(NSBundle * __nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIButton;

SWIFT_CLASS("_TtC7Zone_in24ChooseFishViewController")
@interface ChooseFishViewController : UIViewController
@property (nonatomic, readonly, strong) Singleton * __nonnull sharedData;
@property (nonatomic, weak) IBOutlet UIButton * __null_unspecified babyfishBtn;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (IBAction)babyFishAct:(id __nonnull)sender;
- (IBAction)adultFishAct:(id __nonnull)sender;
- (IBAction)sharkAct:(id __nonnull)sender;
- (void)prepareForSegue:(UIStoryboardSegue * __nonnull)segue sender:(id __nullable)sender;
- (IBAction)close;
- (nonnull instancetype)initWithNibName:(NSString * __nullable)nibNameOrNil bundle:(NSBundle * __nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIImageView;

SWIFT_CLASS("_TtC7Zone_in21ConFishViewController")
@interface ConFishViewController : UIViewController
@property (nonatomic, weak) IBOutlet UIImageView * __null_unspecified fishImage;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (nonnull instancetype)initWithNibName:(NSString * __nullable)nibNameOrNil bundle:(NSBundle * __nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIImage;

SWIFT_CLASS("_TtC7Zone_in25ConfirmPropViewController")
@interface ConfirmPropViewController : UIViewController
@property (nonatomic, weak) IBOutlet UILabel * __null_unspecified testLabel;
@property (nonatomic, weak) IBOutlet UIImageView * __null_unspecified prizeImage;
@property (nonatomic, weak) IBOutlet UIImageView * __null_unspecified backgroundImage;
@property (nonatomic, copy) NSString * __nonnull testText;
@property (nonatomic, copy) NSArray<UIImage *> * __nonnull prizeImageSet;
@property (nonatomic, copy) NSArray<NSString *> * __nonnull labelSet;
- (void)viewDidLoad;
- (void)loadImage;
- (void)updateTestLabel;
- (void)updateImageAndLabel;
- (void)prepareForSegue:(UIStoryboardSegue * __nonnull)segue sender:(id __nullable)sender;
- (IBAction)close;
- (nonnull instancetype)initWithNibName:(NSString * __nullable)nibNameOrNil bundle:(NSBundle * __nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7Zone_in29ConfirmPurchaseViewController")
@interface ConfirmPurchaseViewController : UIViewController
@property (nonatomic, weak) IBOutlet UILabel * __null_unspecified testLabel;
@property (nonatomic, weak) IBOutlet UIImageView * __null_unspecified prizeImage;
@property (nonatomic, copy) NSString * __nonnull testText;
@property (nonatomic, copy) NSArray<UIImage *> * __nonnull prizeImageSet;
@property (nonatomic, copy) NSArray<NSString *> * __nonnull labelSet;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (void)updateTestLabel;
- (void)updateImageAndLabel;
- (IBAction)close;
- (nonnull instancetype)initWithNibName:(NSString * __nullable)nibNameOrNil bundle:(NSBundle * __nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7Zone_in23FirstTimeViewController")
@interface FirstTimeViewController : UIViewController
@property (nonatomic, weak) IBOutlet UITextField * __null_unspecified NameText;
@property (nonatomic, weak) IBOutlet UILabel * __null_unspecified promptLabel;
@property (nonatomic, copy) NSString * __nonnull userName;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (IBAction)toIntroTimerVCAct:(id __nonnull)sender;
- (void)prepareForSegue:(UIStoryboardSegue * __nonnull)segue sender:(id __nullable)sender;
- (nonnull instancetype)initWithNibName:(NSString * __nullable)nibNameOrNil bundle:(NSBundle * __nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class NSTimer;

SWIFT_CLASS("_TtC7Zone_in24IntroCountViewController")
@interface IntroCountViewController : UIViewController
@property (nonatomic, weak) IBOutlet UILabel * __null_unspecified minsLabel;
@property (nonatomic, weak) IBOutlet UILabel * __null_unspecified secsLabel;
@property (nonatomic, weak) IBOutlet UIImageView * __null_unspecified tankImage;
@property (nonatomic, weak) IBOutlet UIImageView * __null_unspecified waterImage;
@property (nonatomic, weak) IBOutlet UIImageView * __null_unspecified fishImage;
@property (nonatomic, weak) IBOutlet UIImageView * __null_unspecified seaweedImage;
@property (nonatomic, strong) NSTimer * __nonnull timer;
@property (nonatomic) NSInteger counter;
@property (nonatomic) NSInteger estCounter;
@property (nonatomic, readonly, strong) Singleton * __nonnull sharedData;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (void)startCounting:(NSInteger)counter;
- (void)updateTime;
- (void)updateLabel:(NSString * __nonnull)mins secs:(NSString * __nonnull)secs;
- (void)updateTankImage:(NSInteger)currNum;
- (nonnull instancetype)initWithNibName:(NSString * __nullable)nibNameOrNil bundle:(NSBundle * __nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UITextView;

SWIFT_CLASS("_TtC7Zone_in24IntroTimerViewController")
@interface IntroTimerViewController : UIViewController
@property (nonatomic, weak) IBOutlet UITextView * __null_unspecified nameBlahLabel;
@property (nonatomic, weak) IBOutlet UIButton * __null_unspecified testButton;
@property (nonatomic, copy) NSString * __nonnull name;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (void)updateName:(NSString * __nonnull)name;
- (IBAction)testvisible:(id __nonnull)sender;
- (void)prepareForSegue:(UIStoryboardSegue * __nonnull)segue sender:(id __nullable)sender;
- (nonnull instancetype)initWithNibName:(NSString * __nullable)nibNameOrNil bundle:(NSBundle * __nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7Zone_in18QuitViewController")
@interface QuitViewController : UIViewController
- (void)viewDidLoad;
- (IBAction)close;
- (nonnull instancetype)initWithNibName:(NSString * __nullable)nibNameOrNil bundle:(NSBundle * __nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7Zone_in25SelectPrizeViewController")
@interface SelectPrizeViewController : UIViewController
@property (nonatomic, readonly, strong) Singleton * __nonnull sharedData;
@property (nonatomic, weak) IBOutlet UIButton * __null_unspecified fishBtn;
@property (nonatomic, weak) IBOutlet UIButton * __null_unspecified seaweedBtn;
@property (nonatomic, weak) IBOutlet UILabel * __null_unspecified testLabel;
- (void)viewDidLoad;
- (IBAction)selectFish:(id __nonnull)sender;
- (IBAction)selectSeaweed:(id __nonnull)sender;
- (IBAction)close;
- (void)didReceiveMemoryWarning;
- (void)prepareForSegue:(UIStoryboardSegue * __nonnull)segue sender:(id __nullable)sender;
- (void)loadImage;
- (nonnull instancetype)initWithNibName:(NSString * __nullable)nibNameOrNil bundle:(NSBundle * __nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7Zone_in24SelectTimeViewController")
@interface SelectTimeViewController : UIViewController
@property (nonatomic, weak) IBOutlet UIImageView * __null_unspecified backTimerImage;
@property (nonatomic, readonly, strong) Singleton * __nonnull sharedData;
@property (nonatomic, weak) IBOutlet UIButton * __null_unspecified moreTimeBtn;
@property (nonatomic, weak) IBOutlet UIButton * __null_unspecified lessTimeBtn;
@property (nonatomic, weak) IBOutlet UILabel * __null_unspecified timeLabel;
@property (nonatomic) NSInteger time;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)animated;
- (IBAction)moreTimeAction:(id __nonnull)sender;
- (IBAction)lessTimeAction:(id __nonnull)sender;
- (void)updateTime:(NSInteger)time;
- (void)prepareForSegue:(UIStoryboardSegue * __nonnull)segue sender:(id __nullable)sender;
- (void)loadImage;
- (IBAction)jumpStoryboardAct:(id __nonnull)sender;
- (IBAction)unwindToMainMenu:(UIStoryboardSegue * __nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * __nullable)nibNameOrNil bundle:(NSBundle * __nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7Zone_in21SetDataViewController")
@interface SetDataViewController : UIViewController
@property (nonatomic, copy) NSString * __nonnull userName;
- (void)viewDidLoad;
- (void)setDefaultData;
- (nonnull instancetype)initWithNibName:(NSString * __nullable)nibNameOrNil bundle:(NSBundle * __nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("Singleton")
@interface Singleton : NSObject
@property (nonatomic) BOOL isLocked;
@property (nonatomic) BOOL isFailed;
@property (nonatomic) NSInteger time;
@property (nonatomic) BOOL babyWithHat;
@property (nonatomic) BOOL adultWithHat;
@property (nonatomic) BOOL adultWithPipe;
@property (nonatomic) BOOL sharkWithHat;
@property (nonatomic) BOOL sharkWithPipe;
+ (Singleton * __nonnull)sharedInstance;
- (void)updateLockStatus:(BOOL)state;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7Zone_in20Store1ViewController")
@interface Store1ViewController : UIViewController
@property (nonatomic, readonly, strong) Singleton * __nonnull sharedDate;
@property (nonatomic, strong) NSTimer * __nonnull timer;
@property (nonatomic) NSInteger counter;
@property (nonatomic, readonly) CGFloat yPosition;
@property (nonatomic, weak) IBOutlet UIImageView * __null_unspecified backgroundImage;
- (void)viewDidLoad;
- (void)loadImage;
- (void)startCounting:(NSInteger)counter;
- (void)updateTime;
- (void)freshFishImage:(NSInteger)counter;
- (void)showOneFish:(UIImageView * __nonnull)fishImage;
- (nonnull instancetype)initWithNibName:(NSString * __nullable)nibNameOrNil bundle:(NSBundle * __nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class NSArray;
@class UIView;

SWIFT_CLASS("_TtC7Zone_in26StoreContentViewController")
@interface StoreContentViewController : UIViewController
@property (nonatomic, weak) IBOutlet UIButton * __null_unspecified button1;
@property (nonatomic, weak) IBOutlet UIButton * __null_unspecified button2;
@property (nonatomic, weak) IBOutlet UIButton * __null_unspecified button3;
@property (nonatomic, weak) IBOutlet UIButton * __null_unspecified button4;
@property (nonatomic, weak) IBOutlet UIView * __null_unspecified constraintView;
@property (nonatomic, strong) NSArray * __nonnull buttonTextArray;
@property (nonatomic) NSInteger pageIndex;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (nonnull instancetype)initWithNibName:(NSString * __nullable)nibNameOrNil bundle:(NSBundle * __nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7Zone_in26StorePageOneViewController")
@interface StorePageOneViewController : UIViewController
@property (nonatomic, weak) IBOutlet UIImageView * __null_unspecified backgroundImage;
@property (nonatomic, weak) IBOutlet UIImageView * __null_unspecified treasureChestImage;
- (void)viewDidLoad;
- (void)loadImage;
- (IBAction)seaweedAct:(id __nonnull)sender;
- (IBAction)cleaningSetAct:(id __nonnull)sender;
- (IBAction)funnyCatAct:(id __nonnull)sender;
- (IBAction)pipeAct:(id __nonnull)sender;
- (void)prepareForSegue:(UIStoryboardSegue * __nonnull)segue sender:(id __nullable)sender;
- (nonnull instancetype)initWithNibName:(NSString * __nullable)nibNameOrNil bundle:(NSBundle * __nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7Zone_in26StorePageTwoViewController")
@interface StorePageTwoViewController : UIViewController
@property (nonatomic, weak) IBOutlet UIImageView * __null_unspecified backgroundImage;
@property (nonatomic, weak) IBOutlet UIImageView * __null_unspecified treasureChestImage;
- (void)viewDidLoad;
- (void)loadImage;
- (IBAction)pillAct:(id __nonnull)sender;
- (void)prepareForSegue:(UIStoryboardSegue * __nonnull)segue sender:(id __nullable)sender;
- (IBAction)close;
- (nonnull instancetype)initWithNibName:(NSString * __nullable)nibNameOrNil bundle:(NSBundle * __nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7Zone_in25StoreParentViewController")
@interface StoreParentViewController : UIViewController
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (nonnull instancetype)initWithNibName:(NSString * __nullable)nibNameOrNil bundle:(NSBundle * __nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIPageViewController;

SWIFT_CLASS("_TtC7Zone_in22StoreSubViewController")
@interface StoreSubViewController : UIViewController <UIPageViewControllerDataSource>
@property (nonatomic, strong) UIPageViewController * __nonnull pageVC;
@property (nonatomic, copy) NSArray<NSArray<NSString *> *> * __nonnull buttonTitles;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (StoreContentViewController * __nonnull)viewControllerAtIndex:(NSInteger)index;
- (UIViewController * __nullable)pageViewController:(UIPageViewController * __nonnull)pageViewController viewControllerBeforeViewController:(UIViewController * __nonnull)viewController;
- (UIViewController * __nullable)pageViewController:(UIPageViewController * __nonnull)pageViewController viewControllerAfterViewController:(UIViewController * __nonnull)viewController;
- (NSInteger)presentationIndexForPageViewController:(UIPageViewController * __nonnull)pageViewController;
- (NSInteger)presentationCountForPageViewController:(UIPageViewController * __nonnull)pageViewController;
- (nonnull instancetype)initWithNibName:(NSString * __nullable)nibNameOrNil bundle:(NSBundle * __nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7Zone_in19TimerViewController")
@interface TimerViewController : UIViewController
@property (nonatomic, weak) IBOutlet UILabel * __null_unspecified minsLabel;
@property (nonatomic, weak) IBOutlet UILabel * __null_unspecified secsLabel;
@property (nonatomic, weak) IBOutlet UIImageView * __null_unspecified tankImage;
@property (nonatomic, weak) IBOutlet UIImageView * __null_unspecified waterImage;
@property (nonatomic, weak) IBOutlet UIImageView * __null_unspecified fishImage;
@property (nonatomic, weak) IBOutlet UIImageView * __null_unspecified seaWeedImage;
@property (nonatomic, strong) NSTimer * __nonnull timer;
@property (nonatomic) NSInteger counter;
@property (nonatomic) NSInteger estCounter;
@property (nonatomic, readonly, strong) Singleton * __nonnull sharedData;
- (void)viewDidLoad;
- (void)startCounting:(NSInteger)counter;
- (void)updateTime;
- (void)updateLabel:(NSString * __nonnull)mins secs:(NSString * __nonnull)secs;
- (void)updateTankImage:(NSInteger)currNum;
- (nonnull instancetype)initWithNibName:(NSString * __nullable)nibNameOrNil bundle:(NSBundle * __nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


@interface UIImage (SWIFT_EXTENSION(Zone_in))
- (UIImage * __nonnull)imageRotatedByDegrees:(CGFloat)degrees flip:(BOOL)flip;
@end


SWIFT_CLASS("_TtC7Zone_in17WinViewController")
@interface WinViewController : UIViewController
@property (nonatomic, weak) IBOutlet UIImageView * __null_unspecified winImage;
@property (nonatomic, strong) UIImage * __nonnull secondImage;
@property (nonatomic, strong) NSTimer * __nonnull timer;
@property (nonatomic) NSInteger counter;
- (void)viewDidLoad;
- (void)startCounting:(NSInteger)counter;
- (void)updateTime;
- (nonnull instancetype)initWithNibName:(NSString * __nullable)nibNameOrNil bundle:(NSBundle * __nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7Zone_in18testViewController")
@interface testViewController : UIViewController
@property (nonatomic, weak) IBOutlet UIImageView * __null_unspecified testImageView;
@property (nonatomic, weak) IBOutlet UILabel * __null_unspecified testLabel;
@property (nonatomic, strong) NSTimer * __nonnull timer;
@property (nonatomic) NSInteger counter;
@property (nonatomic, strong) UIImage * __nonnull secondImage;
- (void)viewDidLoad;
- (void)startCounting:(NSInteger)counter;
- (void)updateTime;
- (void)updateLabel;
- (IBAction)testAnimationAct:(id __nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * __nullable)nibNameOrNil bundle:(NSBundle * __nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

#pragma clang diagnostic pop

